[version("1.0.0"), FriendlyName("DHCPScope")]
class Demo_DHCPScope: MSFT_BaseResourceConfiguration
{
  [Key] string Name;
  [Key] string ID;
  [Key] string StartRange;
  [Key] string EndRange;
  [write] string SubnetMask;
  [write] uint32 LeaseDurationDays;
  [write,ValueMap{"Bootp", "Both", "Dhcp"},Values{"Bootp", "Both", "Dhcp"}] string Type;
  [write,ValueMap{"Active", "InActive"},Values{"Active", "Inactive"}] string State;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};