[version("1.0.0"), FriendlyName("IPAddress")] 
class Demo_IPAddress : MSFT_BaseResourceConfiguration
{
  [Key] string IPAddress;
  [Key] string InterfaceAlias;
  [write] string DefaultGateway;
  [Write] uint32 PrefixLength;
  [Write,ValueMap{"IPv4", "IPv6"},Values{"IPv4", "IPv6"}] string AddressFamily;
  [Write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};